name: Linter

on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Move Directory
        run: cd ./my-app
      - name: Run npm ci
        run: npm ci
      - name: Run Biome
        run: npx @biomejs/biome check --write ./app
