name: Linter

on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest
          working-dir: ./my-app
      
      - name: Run Biome
        run: biome ci
