name: Linter

on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    steps:
      - name: Move Directory
        run: cd ./my-app

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      
      - name: Run Biome
        run: biome ci
